### ISSUE TITLE
Switch view backend save error

### ISSUE THREAD

**Issue by nedx86** [filebrowser/filebrowser#2012]
**Description**
If i try to click "switch view" button i got red "html alert":
000 No connection

bare run, docker run - same result
if use nginx - 502 bad gateway error

it's looks like PUT problem or user save

console go errors:
...
filebrowser/v2/storage/bolt.usersBackend.Update
...

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration, server and browser logs. Also ensure that your proxy is not introducing issues by accessing FileBrowser directly.

**Comment by jlucansky** [comment]
Same issue here.

HTTP request:
```
PUT /api/users/1 HTTP/1.1
Host: files.redacted.com
Remote-User: redacted
Remote-Groups: admins
Remote-Name: redacted
Remote-Email: redacted@gmail.com
Content-Length: 70
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
X-Auth: redacted
Content-Type: text/plain;charset=UTF-8
Accept: */*
Sec-GPC: 1
Origin: https://files.redacted.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://files.redacted.com
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: authelia_session=redacted
X-Forwarded-Proto: https
X-Forwarded-For: redacted

{"what":"user","which":["viewMode"],"data":{"id":1,"viewMode":"list"}}
```

FileBrowser log:
```
2022/07/01 20:07:55 http: panic serving 192.168.1.123:58287: reflect: call of reflect.Value.Interface on zero Value
goroutine 47 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:1825 +0xbf
panic({0x97dda0, 0xc00023d638})
        /opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:844 +0x258
reflect.valueInterface({0x0?, 0x0?, 0x1?}, 0x78?)
        /opt/hostedtoolcache/go/1.18.3/x64/src/reflect/value.go:1435 +0x10e
reflect.Value.Interface(...)
        /opt/hostedtoolcache/go/1.18.3/x64/src/reflect/value.go:1430
github.com/filebrowser/filebrowser/v2/storage/bolt.usersBackend.Update({0xc000388410?}, 0xc000388410, {0xc0001cfdc0?, 0x1, 0x0?})
        /home/runner/work/filebrowser/filebrowser/storage/bolt/users.go:61 +0x190
github.com/filebrowser/filebrowser/v2/users.(*Storage).Update(0xc0001a4c60, 0xc000388410, {0xc0001cfdc0, 0x1, 0x4})
        /home/runner/work/filebrowser/filebrowser/users/storage.go:81 +0x83
github.com/filebrowser/filebrowser/v2/http.glob..func23({0x1382ab8?, 0xc000155960?}, 0x17c0340?, 0xc0001cfd00)
        /home/runner/work/filebrowser/filebrowser/http/users.go:201 +0x2af
github.com/filebrowser/filebrowser/v2/http.withSelfOrAdmin.func1({0x1382ab8, 0xc000155960}, 0x3?, 0xc0001cfd00)
        /home/runner/work/filebrowser/filebrowser/http/users.go:66 +0xc2
github.com/filebrowser/filebrowser/v2/http.withUser.func1({0x1382ab8, 0xc000155960}, 0xa41dd4?, 0xc0001cfd00)
        /home/runner/work/filebrowser/filebrowser/http/auth.go:88 +0x387
github.com/filebrowser/filebrowser/v2/http.handle.func1({0x1382ab8, 0xc000155960}, 0xc000265c00)
        /home/runner/work/filebrowser/filebrowser/http/data.go:60 +0x242
net/http.HandlerFunc.ServeHTTP(0x9e3460?, {0x1382ab8?, 0xc000155960?}, 0x17?)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x2f
github.com/filebrowser/filebrowser/v2/http.NewHandler.func1.1({0x1382ab8, 0xc000155960}, 0xc0002631d0?)
        /home/runner/work/filebrowser/filebrowser/http/http.go:31 +0xf4
net/http.HandlerFunc.ServeHTTP(0xc000265b00?, {0x1382ab8?, 0xc000155960?}, 0x0?)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000176240, {0x1382ab8, 0xc000155960}, 0xc000265a00)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x1380bc0?}, {0x1382ab8, 0xc000155960}, 0xc000265a00)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001e6b40, {0x1383258, 0xc0001d9230})
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:3071 +0x4db
```

**Comment by kirnehv** [comment]
Having the same issue here with Linux and Windows versions.

Same issue when trying to click "Update" in "Profile Settings":

![image](https://user-images.githubusercontent.com/34227590/177002033-ce83ebd6-4e6a-43d9-9e56-89c9da259875.png)

Seems like others are also reporting this issue: #2015, #2016, #2017

**Comment by masterwishx** [comment]
Also have this problem on save profil in both local (http://192.168.0.199:8889/) and web (files.mysite.com) sites 

![image](https://user-images.githubusercontent.com/28630321/177049629-682dfb11-eda0-4a35-9190-36d96c5a5933.png)

![image](https://user-images.githubusercontent.com/28630321/177049656-066382ea-6aef-4e24-ae48-85be96280849.png)

![image](https://user-images.githubusercontent.com/28630321/177049736-6d929202-3690-4f77-a7d9-6f5dcfed8d67.png)

![image](https://user-images.githubusercontent.com/28630321/177049765-8ffc27d9-36c0-4f5f-99f7-b661a325c14c.png)

**Comment by ramiresviana** [comment]
This issue was introduced on v2.22.2 and needs to be fixed. For those who are affected by this, you can downgrade to the previous release until a fix is released.
