### ISSUE TITLE
Frontend build failure: error:0308010C:digital envelope routines::unsupported (nodejs 16.16)

### ISSUE THREAD

**Issue by i0ntempest** [filebrowser/filebrowser#2029]
**Description**
Build filebrowser

**Expected behaviour**
Build success

**What is happening instead?**
```
:info:build > filebrowser-frontend@2.0.0 build
:info:build > find ./dist -maxdepth 1 -mindepth 1 ! -name '.gitignore' -exec rm -r {} + && vue-cli-service build --no-clean
:info:build -  Building for production...
:info:build Error: error:0308010C:digital envelope routines::unsupported
:info:build     at new Hash (node:internal/crypto/hash:67:19)
:info:build     at Object.createHash (node:crypto:130:10)
:info:build     at module.exports (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
:info:build     at NormalModule._initBuildHash (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
:info:build     at handleParseError (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:503:5
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:358:12
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
:info:build     at iterateNormalLoaders (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
:info:build     at iterateNormalLoaders (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
:info:build     at runSyncOrAsync (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
:info:build     at iterateNormalLoaders (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
:info:build     at Array.<anonymous> (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
:info:build     at Storage.finished (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:114
:info:build 			throw e;
:info:build 			^
:info:build Error: error:0308010C:digital envelope routines::unsupported
:info:build     at new Hash (node:internal/crypto/hash:67:19)
:info:build     at Object.createHash (node:crypto:130:10)
:info:build     at module.exports (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
:info:build     at NormalModule._initBuildHash (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
:info:build     at handleParseError (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:503:5
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/webpack/lib/NormalModule.js:358:12
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
:info:build     at iterateNormalLoaders (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
:info:build     at iterateNormalLoaders (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
:info:build     at context.callback (/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/cache-loader/dist/index.js:147:7
:info:build     at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_filebrowser/filebrowser/work/gopath/src/github.com/filebrowser/filebrowser/frontend/node_modules/graceful-fs/graceful-fs.js:61:14
:info:build     at FSReqCallback.oncomplete (node:fs:188:23) {
:info:build   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
:info:build   library: 'digital envelope routines',
:info:build   reason: 'unsupported',
:info:build   code: 'ERR_OSSL_EVP_UNSUPPORTED'
:info:build }
```

**Additional context**
Seems this is a widespread compatibility issue caused by OpenSSL. I tried workaround `--openssl-legacy-provider` but that resulted in `--openssl-legacy-provider is not allowed in NODE_OPTIONS`

**How to reproduce?**
Build filebrowser frontend with newest nodejs16

**Files**

**Comment by o1egl** [comment]
Can't reproduce it with `v16.14.0`

**Comment by i0ntempest** [comment]
> Can't reproduce it with `v16.14.0`

Exactly, this is new with 16.16, and my environment does not really allow downgrading.

**Comment by o1egl** [comment]
I can't reproduce it on v16.16.0 either. I think you have an issue with your nodejs setup

**Comment by i0ntempest** [comment]
> I can't reproduce it on v16.16.0 either. I think you have an issue with your nodejs setup

Ok I'll check with MacPorts members with what changed in their nodejs. Also does filebrowser supports nodejs 17 and 18?

**Comment by o1egl** [comment]
It is not officially supported

**Comment by cmprmsd** [comment]
I had this issue also on node v16.18.
`export NODE_OPTIONS=--openssl-legacy-provider` [helped](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported).
