### ISSUE TITLE
page not load, js  error

### ISSUE THREAD

**Issue by c608345** [filebrowser/filebrowser#2386]
**Description**
Fresh install, js error

**Expected behaviour**
works

**What is happening instead?**
Uncaught SyntaxError: Unexpected token '<' (at chunk-vendors.0f8eac7b.js:1:1)
Uncaught SyntaxError: Unexpected token '<' (at app.8ca2bdf9.js:1:1)

**How to reproduce?**
Install and  config, visit homepage  in browser.

**Files**
v2.23.0 linux-amd64-filebrowser.tar.gz
![9034573045](https://user-images.githubusercontent.com/37238933/226794661-5a2f628d-81f0-4fa1-ac32-7c4e760604b0.png)

**Comment by c608345** [comment]
I set the baseurl to full domain. Reset baseurl solved the issue.
