### ISSUE TITLE
Unable to set auth method to proxy

### ISSUE THREAD

**Issue by kekersdev** [filebrowser/filebrowser#2898]
**Description**
Using `filebrowser config set --auth.method` it is possible to set auth method to `json` or `noauth` but not the `proxy`

**Expected behaviour**
```
/ # ./filebrowser config set --auth.method proxy
Sign up:          false
Create User Dir:  false
Auth method:      proxy
```

**What is happening instead?**
```
/ # ./filebrowser config set --auth.method proxy
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.getAuthentication(0xc0000d0500?, {0xc000119c28, 0x3, 0x7f092ec065b8?})
        /home/runner/work/filebrowser/filebrowser/cmd/config.go:77 +0x746
github.com/filebrowser/filebrowser/v2/cmd.glob..func9(0x0?, {0x0?, 0x0?, 0x0?}, {0x0?, 0xc00012d5c0?})
        /home/runner/work/filebrowser/filebrowser/cmd/config_set.go:72 +0x248
github.com/filebrowser/filebrowser/v2/cmd.init.python.func9(0xc0000d0500?, {0xc0000c2940, 0x0, 0x2})
        /home/runner/work/filebrowser/filebrowser/cmd/utils.go:106 +0x203
github.com/spf13/cobra.(*Command).execute(0x1269a80, {0xc0000c2920, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x126a040)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/filebrowser/filebrowser/v2/cmd.Execute()
        /home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x1a
main.main()
        /home/runner/work/filebrowser/filebrowser/main.go:8 +0xf
```

**Additional context**
As mentioned earlier, options `json` and `noauth` work as expected:
```
/ # ./filebrowser config set --auth.method noauth
Sign up:          false
Create User Dir:  false
Auth method:      noauth
```

**How to reproduce?**
`filebrowser config set --auth.method proxy`

**Files**
-

**Comment by kekersdev** [comment]
Turns out `--auth.header` **must** be used in the same `config set` call if the `--auth.method` is being set to `proxy`
So it is either
`filebrowser config set --auth.method noauth`
or
`filebrowser config set --auth.method json`
or
`filebrowser config set --auth.method proxy --auth.header X-Some-Header`
