### ISSUE TITLE
Docker installation failed

### ISSUE THREAD

**Issue by wuyandefeixue** [filebrowser/filebrowser#3318]
Failed to install using Docker。

Refer to the official installation tutorial，refer to https://filebrowser.org/installation#docker.

First, create the directory and files you want to mount。
```shell
cd /data
mkdir filebrowser
cd filebrowser
touch filebrowser.db
touch settings.json
vim settings.json
#Add JSON configuration, refer to https://github.com/filebrowser/filebrowser/blob/master/docker/root/defaults/settings.json
#{
#  "port": 80,
#  "baseURL": "",
#  "address": "",
#  "log": "stdout",
#  "database": "/database/filebrowser.db",
#  "root": "/srv"
#}
#save and exit
#Modifying Docker Installation Script
#Modifying ports and mounting addresses
docker run \
    -v /data/filebrowser/root:/srv \
    -v /data/filebrowser/filebrowser.db:/database/filebrowser.db \
    -v /data/filebrowser/settings.json:/config/settings.json \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    -p 7080:80 \
    filebrowser/filebrowser:s6
``` 
After executing the script, the Docker run, but the status was unhealthy and I couldn't quite understand the logs.
This is the log information. To solve the problem, I restarted this Docker container
```shell
$ docker logs 163fbcbe3ff5-f --tail=200
goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x346
github.com/spf13/cobra.(*Command).preRun(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x42
github.com/spf13/cobra.(*Command).execute(0x1825440, {0xc0000c2010, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x25
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x2a
panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x346
github.com/spf13/cobra.(*Command).preRun(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x42
github.com/spf13/cobra.(*Command).execute(0x1825440, {0xc0000300b0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x25
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x2a
panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x346
github.com/spf13/cobra.(*Command).preRun(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x42
github.com/spf13/cobra.(*Command).execute(0x1825440, {0xc0000300b0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x25
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x2a
panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x346
github.com/spf13/cobra.(*Command).preRun(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x42
github.com/spf13/cobra.(*Command).execute(0x1825440, {0xc0000c2010, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x25
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x2a
panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x346
github.com/spf13/cobra.(*Command).preRun(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x42
github.com/spf13/cobra.(*Command).execute(0x1825440, {0xc0000300b0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x25
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x2a
panic: While parsing config: unexpected end of JSON input

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.initConfig()
	/home/runner/work/filebrowser/filebrowser/cmd/root.go:404 +0x346
github.com/spf13/cobra.(*Command).preRun(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:856 +0x42
github.com/spf13/cobra.(*Command).execute(0x1825440, {0xc0000300b0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:792 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x1825440)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
	/home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x25
main.main()
	/home/runner/work/filebrowser/filebrowser/main.go:11 +0x2a
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2024/06/18 10:11:05 Using config file: /config/settings.json
2024/06/18 10:11:05 Listening on [::]:8080
2024/06/18 10:11:58 Caught signal terminated: shutting down.
2024/06/18 10:11:58 accept tcp [::]:8080: use of closed network connection
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2024/06/18 10:17:09 Using config file: /config/settings.json
2024/06/18 10:17:09 Listening on [::]:8080

```

**Comment by Rapter001** [comment]
to make it easier to manage docker quickly use portainer and use the official docker image from file browser [https://hub.docker.com/r/filebrowser/filebrowser](url)

**Comment by mbluett88** [comment]
If you indeed put # (hash signs) in front of all the items you added to your settings.json file then that would be why you are seeing the error "unexpected end of JSON input". All lines starting with a # will be ignored. You need to remove them. Use them only for comments. But, in the case of this file you really don't need any comments.

**Comment by wuyandefeixue** [comment]
> If you indeed put # (hash signs) in front of all the items you added to your settings.json file then that would be why you are seeing the error "unexpected end of JSON input". All lines starting with a # will be ignored. You need to remove them. Use them only for comments. But, in the case of this file you really don't need any comments.

I understand that adding a # sign is only to indicate editing status. In fact, when saving a file, there is no # sign.
I switched to the filebrowser/filebrowser version, and it seems like there's no problem. I'm not sure if there's a problem with filebrowser/filebrowser: s6
