### ISSUE TITLE
Can't create folder to move selected files

### ISSUE THREAD

**Issue by mostepunk** [filebrowser/filebrowser#3621]
**Description**
I selected several files and after that I want to move it into new folder. But when I'm clicking create folder, nothing happens.

**Expected behaviour**
It would be nice, that new folder creates

**What is happening instead?**
no logs

**Comment by aclerici38** [comment]
Facing this as well. Console logs from  Zen Browser 1.0.2-b.0 (Firefox 133.0):
`TypeError: this.$store is undefined
    createDir https://filebrowser.mydomain.com/static/assets/index-B6-dpoh6.js:26
    1 https://filebrowser.mydomain.com/static/assets/index-B6-dpoh6.js:26
    vn https://filebrowser.mydomain.com/static/assets/i18n-sWEFv6SY.js:13
    je https://filebrowser.mydomain.com/static/assets/i18n-sWEFv6SY.js:13
    r https://filebrowser.mydomain.com/static/assets/i18n-sWEFv6SY.js:17
i18n-sWEFv6SY.js:13:589
    Us https://filebrowser.mydomain.com/static/assets/i18n-sWEFv6SY.js:13
    Mr https://filebrowser.mydomain.com/static/assets/i18n-sWEFv6SY.js:13
    je https://filebrowser.mydomain.com/static/assets/i18n-sWEFv6SY.js:13
`
And from Chrome 131.0.6778.109:
`TypeError: Cannot read properties of undefined (reading 'commit')
    at Proxy.createDir (index-B6-dpoh6.js:26:12286)
    at e.user.perm.create.I.onClick.t.<computed>.t.<computed> (index-B6-dpoh6.js:26:18202)
    at vn (i18n-sWEFv6SY.js:13:38)
    at je (i18n-sWEFv6SY.js:13:108)
    at HTMLButtonElement.r (i18n-sWEFv6SY.js:17:7459)`

I am running Filebrowser v2.31.2 in k3s on Debian

**Comment by aclerici38** [comment]
This is still an issue /remove-lifecycle stale
