### ISSUE TITLE
Documentation example doesn't work

### ISSUE THREAD

**Issue by klingtnet** [filebrowser/filebrowser#63]
I am using caddy 0.8.2 with all features enabled.

Here is my simple test config:

``` ini
localhost:80
root /tmp/hugo
hugo
```

Here is the output of caddy:

``` sh
/tmp: caddy -conf /tmp/caddy.conf
Activating privacy features... done.
Usage:
  hugo new site [path] [flags]

Flags:
  -f, --format="toml": config & frontmatter format

Global Flags:
  -b, --baseURL="": hostname (and path) to the root, e.g. http://spf13.com/
  -D, --buildDrafts[=false]: include content marked as draft
  -F, --buildFuture[=false]: include content with publishdate in the future
      --cacheDir="": filesystem path to cache directory. Defaults: $TMPDIR/hugo_cache/
      --config="": config file (default is path/config.yaml|json|toml)
  -d, --destination="": filesystem path to write files to
      --disableRSS[=false]: Do not build RSS files
      --disableSitemap[=false]: Do not build Sitemap file
      --editor="": edit new content with this editor, if provided
      --ignoreCache[=false]: Ignores the cache directory for reading but still writes to it
      --log[=false]: Enable Logging
      --logFile="": Log File path (if set, logging enabled automatically)
      --pluralizeListTitles[=true]: Pluralize titles in lists using inflect
      --preserveTaxonomyNames[=false]: Preserve taxonomy names as written ("Gérard Depardieu" vs "gerard-depardieu")
  -s, --source="": filesystem path to read files relative from
      --stepAnalysis[=false]: display memory and timing of different steps of the program
  -t, --theme="": theme to use (located in /themes/THEMENAME/)
      --uglyURLs[=false]: if true, use /filename.html instead of /filename/
  -v, --verbose[=false]: verbose output
      --verboseLog[=false]: verbose logging

Error: unknown flag: --force
CRITICAL: 2016/03/05 unknown flag: --force
panic: exit status 255

goroutine 1 [running]:
panic(0xb02140, 0xc82014cef0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
log.Panic(0xc8201014f0, 0x1, 0x1)
    /usr/local/go/src/log/log.go:320 +0xc1
github.com/hacdias/caddy-hugo.Setup(0xc820086800, 0xc8201ce070, 0x0, 0x0)
    /home/caddy/go/src/github.com/hacdias/caddy-hugo/hugo.go:50 +0x3ff
github.com/mholt/caddy/caddy.loadConfigs(0x7ffc161e152b, 0xa, 0x7f773429a4e0, 0xc8200f7d10, 0x0, 0x0, 0x0, 0x0, 0x0)
    /tmp/custombuild_1212_768707807/src/github.com/mholt/caddy/caddy/config.go:166 +0xa15
github.com/mholt/caddy/caddy.Start(0x7f773429abc8, 0xc8200f7ce0, 0x0, 0x0)
    /tmp/custombuild_1212_768707807/src/github.com/mholt/caddy/caddy/caddy.go:140 +0x2aa
main.main()
    /tmp/custombuild_1212_768707807/src/github.com/mholt/caddy/main.go:103 +0x61f
```

**Comment by hacdias** [comment]
Hey @klingtnet 

What's the version of Hugo that's installed on your computer? Was it downloaded when you first executed Caddy with caddy-hugo plugin?

**Edit:**

If your Caddy configuration file is:

```
localhost:80
root /tmp/hugo
hugo
```

And your are running on /tmp, you mean: the static files will be on /tmp/hugo and Hugo website will be created/or is on /tmp. I think you wanted to mean something like this:

```
localhost:80
root /tmp/hugo/public
hugo /tmp/hugo
```

Try it, please.

**Comment by klingtnet** [comment]
Hi @hacdias

Hugo was downloaded: `/home/MYUSERNAME/.go/bin/hugo`.
I've changed the paths in my config file like you proposed to do, but the problem is still the same.

``` sh
/tmp: caddy -conf /tmp/caddy.conf
Activating privacy features... done.
Usage:
  hugo new site [path] [flags]

Flags:
  -f, --format="toml": config & frontmatter format

Global Flags:
  -b, --baseURL="": hostname (and path) to the root, e.g. http://spf13.com/
  -D, --buildDrafts[=false]: include content marked as draft
  -F, --buildFuture[=false]: include content with publishdate in the future
      --cacheDir="": filesystem path to cache directory. Defaults: $TMPDIR/hugo_cache/
      --config="": config file (default is path/config.yaml|json|toml)
  -d, --destination="": filesystem path to write files to
      --disableRSS[=false]: Do not build RSS files
      --disableSitemap[=false]: Do not build Sitemap file
      --editor="": edit new content with this editor, if provided
      --ignoreCache[=false]: Ignores the cache directory for reading but still writes to it
      --log[=false]: Enable Logging
      --logFile="": Log File path (if set, logging enabled automatically)
      --pluralizeListTitles[=true]: Pluralize titles in lists using inflect
      --preserveTaxonomyNames[=false]: Preserve taxonomy names as written ("Gérard Depardieu" vs "gerard-depardieu")
  -s, --source="": filesystem path to read files relative from
      --stepAnalysis[=false]: display memory and timing of different steps of the program
  -t, --theme="": theme to use (located in /themes/THEMENAME/)
      --uglyURLs[=false]: if true, use /filename.html instead of /filename/
  -v, --verbose[=false]: verbose output
      --verboseLog[=false]: verbose logging

Error: unknown flag: --force
CRITICAL: 2016/03/05 unknown flag: --force
panic: exit status 255

goroutine 1 [running]:
panic(0xb02140, 0xc820150d70)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
log.Panic(0xc8201014f0, 0x1, 0x1)
    /usr/local/go/src/log/log.go:320 +0xc1
github.com/hacdias/caddy-hugo.Setup(0xc820088680, 0xc8200f7f30, 0x0, 0x0)
    /home/caddy/go/src/github.com/hacdias/caddy-hugo/hugo.go:50 +0x3ff
github.com/mholt/caddy/caddy.loadConfigs(0x7ffd056d452b, 0xa, 0x7f10fe2d64e0, 0xc8200f7d10, 0x0, 0x0, 0x0, 0x0, 0x0)
    /tmp/custombuild_1212_768707807/src/github.com/mholt/caddy/caddy/config.go:166 +0xa15
github.com/mholt/caddy/caddy.Start(0x7f10fe2d6bc8, 0xc8200f7ce0, 0x0, 0x0)
    /tmp/custombuild_1212_768707807/src/github.com/mholt/caddy/caddy/caddy.go:140 +0x2aa
main.main()
    /tmp/custombuild_1212_768707807/src/github.com/mholt/caddy/main.go:103 +0x61f
```

**Comment by klingtnet** [comment]
``` sh
hugo version  
Hugo Static Site Generator v0.15-DEV BuildDate: 2015-09-22T16:36:41+02:00
```

**Comment by klingtnet** [comment]
Running hugo help:

``` sh
 /tmp: hugo --version
Usage:
  hugo [flags]
  hugo [command]

Available Commands:
  server          Hugo runs its own webserver to render the files
  version         Print the version number of Hugo
  config          Print the site configuration
  check           Check content in the source directory
  benchmark       Benchmark hugo by building a site a number of times.
  convert         Convert your content to different formats
  new             Create new content for your site
  list            Listing out various types of content
  undraft         Undraft changes the content's draft status from 'True' to 'False'
  genautocomplete Generate shell autocompletion script for Hugo
  gendoc          Generate Markdown documentation for the Hugo CLI.

Flags:
  -b, --baseURL="": hostname (and path) to the root, e.g. http://spf13.com/
  -D, --buildDrafts[=false]: include content marked as draft
  -F, --buildFuture[=false]: include content with publishdate in the future
      --cacheDir="": filesystem path to cache directory. Defaults: $TMPDIR/hugo_cache/
      --config="": config file (default is path/config.yaml|json|toml)
  -d, --destination="": filesystem path to write files to
      --disableRSS[=false]: Do not build RSS files
      --disableSitemap[=false]: Do not build Sitemap file
      --editor="": edit new content with this editor, if provided
      --ignoreCache[=false]: Ignores the cache directory for reading but still writes to it
      --log[=false]: Enable Logging
      --logFile="": Log File path (if set, logging enabled automatically)
      --noTimes[=false]: Don't sync modification time of files
      --pluralizeListTitles[=true]: Pluralize titles in lists using inflect
      --preserveTaxonomyNames[=false]: Preserve taxonomy names as written ("Gérard Depardieu" vs "gerard-depardieu")
  -s, --source="": filesystem path to read files relative from
      --stepAnalysis[=false]: display memory and timing of different steps of the program
  -t, --theme="": theme to use (located in /themes/THEMENAME/)
      --uglyURLs[=false]: if true, use /filename.html instead of /filename/
  -v, --verbose[=false]: verbose output
      --verboseLog[=false]: verbose logging
  -w, --watch[=false]: watch filesystem for changes and recreate as needed

Use "hugo [command] --help" for more information about a command.

Error: unknown flag: --version
CRITICAL: 2016/03/05 unknown flag: --version
```

**Comment by klingtnet** [comment]
I'm suppose that you're downloading `hugo` with `go get -d` on the first run of `caddy-hugo`?
The version from there seems to be fairly old.

**UPDATE**: There is no alias:

``` sh
$ command -v hugo
/home/MYUSERNAME/.go/bin/hugo
```

**Comment by hacdias** [comment]
> The version from there seems to be fairly old.

What? From where? The latest stable version is 0.15!

---

As you can see [here](https://github.com/hacdias/caddy-hugo/blob/master/hugo/hugo.go#L54), the plugin checks if Hugo is in the Path. If so, it will return its path and use that version of Hugo. If it doesn't, he will check if it's on `$HOME/.caddy/bin`. If it doesn't, it will be downloaded from GitHub releases (the same that are available at gohugo.io) to that location and return the path of the executable.

---

Remove everything from `$HOME/.caddy/bin` and remove all the Hugo executables you have on your computer.

The error you are receiving doesn't make any sense because the command that is being executed is `hugo new site /tmp/hugo --force`. Unless you have a very old version on your computer that doesn't support `--force` flag, I can't understand what's going on.

---

Download Caddy + Caddy-Hugo from [this repository](https://dl.bintray.com/hacdias/generic/caddy-hugo/1457123545/) because [caddyserver.com](http://caddyserver.com) still doesn't have the latest updates of caddy-hugo. **CC:** @mholt

**Comment by klingtnet** [comment]
@hacdias 

You're right, I had installed `hugo` sometime ago. I removed all previous `hugo` installations (to be clear, it was only one :smile: ) but the automatic installation of `hugo` fails:

``` sh
/tmp: caddy -conf /tmp/caddy.conf
Activating privacy features... done.
Unable to find Hugo on your computer.
Downloading Hugo from GitHub releases... downloaded.
Checking SHA256...checked!
Unziping... open /tmp/caddy-hugo127013417: is a directory

/tmp: ll caddy-hugo127013417 
total 4,4M
-rwxrwxr-- 1 MYUSERNAME users 4,4M  5. Mär 15:43 hugo_0.15_linux_amd64.tar.gz
```

PS: There is a missing `p` in `Unziping`.

**Comment by hacdias** [comment]
Hey @klingtnet 

Download `caddy` + `caddy-hugo` from [here](https://dl.bintray.com/hacdias/generic/caddy-hugo). Download from the last folder. The version on caddyserver.com has that bug. I'm waiting for @mholt to update it whenever he can.

The link above only has caddy-hugo plugin. It's automatically built every time this repository is updated. I fixed that yesterday, so the executables in that link should work.

And thanks! I'll add a "p".

**Comment by klingtnet** [comment]
The tarball is broken:

``` sh
/tmp: curl -Lsf 'https://dl.bintray.com/hacdias/generic/caddy-hugo/1457123545/:caddy_linux_amd64.tar.gz' | tar -C ~/bin -xvzf - -- hugo

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by hacdias** [comment]
Why those double dots? The link should be `https://dl.bintray.com/hacdias/generic/caddy-hugo/1457123545/caddy_linux_amd64.tar.gz` and not `https://dl.bintray.com/hacdias/generic/caddy-hugo/1457123545/:caddy_linux_amd64.tar.gz`. I can open it here.

**Comment by klingtnet** [comment]
I copied the link directly from the site.

**Comment by klingtnet** [comment]
The fixed link works:

``` sh
/tmp: curl -Lsf 'https://dl.bintray.com/hacdias/generic/caddy-hugo/1457123545/caddy_linux_amd64.tar.gz' | tar -C ~/bin -xvzf - -- caddy 
caddy
```

Be patient, I will try to run this caddy version.

**Comment by hacdias** [comment]
O.o I see. Don't know why they use the colon on download page. 

Sure :)

**Comment by klingtnet** [comment]
Running from `tmp` won't work because you're trying to create a hard link that crosses device boundaries:

``` sh
/tmp: caddy -conf /tmp/caddy.conf
Activating privacy features... done.
Unable to find Hugo on your computer.
Downloading Hugo from GitHub releases... downloaded.
Checking SHA256...checked!
Unziping... done.
rename /tmp/caddy-hugo156319884/hugo_0.15_linux_amd64/hugo_0.15_linux_amd64 /home/MYUSERNAME/.caddy/bin/hugo: invalid cross-device link
```

Running from a different folder (inside my userhome) won't work as well, because you're downloading to `/tmp` which is usually a `tmpfs`.

``` sh
~/tmp/caddy-hugo: caddy -conf ./caddy.conf
Activating privacy features... done.
Unable to find Hugo on your computer.
Downloading Hugo from GitHub releases... downloaded.
Checking SHA256...checked!
Unziping... done.
rename /tmp/caddy-hugo000115982/hugo_0.15_linux_amd64/hugo_0.15_linux_amd64 /home/MYUSERNAME/.caddy/bin/hugo: invalid cross-device link
```

**Comment by klingtnet** [comment]
Proposed solution: Copy the binary and remove the `/tmp` directory.

**Comment by hacdias** [comment]
Thanks. I'll change that [here](https://github.com/hacdias/caddy-hugo/blob/master/hugo/hugo.go#L106). :)

**Comment by klingtnet** [comment]
You're welcome. Can't wait to try out the `hugo` admin panel because this is basically what I wanted to develop myself before I discovered `caddy`.

**Comment by hacdias** [comment]
After [this](https://travis-ci.org/hacdias/caddy-hugo/builds/113905151) build is finished, the new binaries will be available on the same link as the others.

I hope you enjoy the admin interface! And help building it, if you want to =D

**Comment by klingtnet** [comment]
I've a lot of other work to do at the moment, but I will try to contribute when I got some spare time.

**Comment by hacdias** [comment]
New v. already available! :D

**Comment by klingtnet** [comment]
Yeah, I already noticed :+1: 

You forget to set the executable bit of `~/.caddy/bin/hugo` after downloading it. After setting the bit, everything works fine!

Installation steps (for anyone else):

``` sh
curl -Lsf 'https://dl.bintray.com/hacdias/generic/caddy-hugo/1457193456/caddy_linux_amd64.tar.gz' | tar -C ~/bin -xvzf - -- caddy
caddy -conf ./caddy.conf
chmod +x ~/.caddy/bin/hugo
caddy -conf ./caddy.conf
```

**Comment by hacdias** [comment]
> You forget to set the executable of ~/.caddy/bin/hugo after downloading it. After setting the flag, everything works fine!

I'm not unedrstanding. Forget what? The chmod stuff?

**Comment by klingtnet** [comment]
Yeah, correctly.

**Comment by hacdias** [comment]
Oh... I'll add that :D Thanks. I think I can close the issue now. Enjoy it!

**Comment by klingtnet** [comment]
Ok, thanks for your work!

**Comment by hacdias** [comment]
You're welcome!
