### ISSUE TITLE
New version is crashing

### ISSUE THREAD

**Issue by djxy** [filebrowser/filebrowser#736]
**Description**
I'm trying to start the application but it crash.

**Expected behaviour**
The application should start.

**What is happening instead?**
```
Downloading File Browser for linux/amd64...
https://github.com/filebrowser/filebrowser/releases/download/v2.0.10/linux-amd64-filebrowser.tar.gz
Extracting...
Putting filemanager in /usr/local/bin (may require password)
Successfully installed
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/filebrowser/filebrowser/v2/cmd.getAuthentication(0xc000096500, 0x0, 0x0, 0x0, 0xc0001afb98, 0x203000, 0x203000, 0xc0001afb88)
        /home/circleci/project/cmd/config.go:92 +0x9d9
github.com/filebrowser/filebrowser/v2/cmd.glob..func8(0x22f3520, 0x231eb50, 0x0, 0x0, 0x0, 0xc00000d980)
        /home/circleci/project/cmd/config_init.go:29 +0xbb
github.com/filebrowser/filebrowser/v2/cmd.python.func1(0x22f3520, 0x231eb50, 0x0, 0x0)
        /home/circleci/project/cmd/utils.go:102 +0x230
github.com/spf13/cobra.(*Command).execute(0x22f3520, 0x231eb50, 0x0, 0x0, 0x22f3520, 0x231eb50)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x22f39e0, 0xc0001aff68, 0x4069dd, 0x23020b0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/filebrowser/filebrowser/v2/cmd.Execute()
        /home/circleci/project/cmd/cmd.go:9 +0x2e
main.main()
        /home/circleci/project/main.go:11 +0x33
2019/05/20 21:21:47 No config file used
2019/05/20 21:21:47 the resource does not exist
```

**Additional context**
The script that I use to start it.

```
#!/bin/sh

if [ ! -f /filebrowser/config ]; then
    curl -fsSL https://filebrowser.xyz/get.sh | bash
    filebrowser config init
    filebrowser config set --address 0.0.0.0
    filebrowser config set --port 8080
    filebrowser config set --config /filebrowser/config
    filebrowser config set --database /filebrowser/database
    filebrowser config set --root /data
    filebrowser users add admin $PASSWORD
fi

filebrowser
```

**Comment by hacdias** [comment]
Thanks for reporting. Please use v2.0.9 in the meanwhile. @unicod3 could you please take a look at this? It's related to your recent PR. If you can't, I'll take a look on the weekend.

**Comment by djxy** [comment]
Is there a way to specify the version  when downloading?

**Comment by unicod3** [comment]
@hacdias  yes, I saw that I am already looking into that, btw can you put some test files, because I am not familiar with all the cases for config set.

**Comment by unicod3** [comment]
@djxy  I just created a PR, checked your case, sorry for the issue. You can get the new version as soon as this PR merges.

@hacdias  maybe you should consider opening a new development branch where we can break things :)

**Comment by hacdias** [comment]
@djxy oh, I thought you were using Docker, so it would be easy. Now I noticed your using the installation script. V2.0.11 is on the way!
