### ISSUE TITLE
window xp下 从2.03升级到2.12无法运行了

### ISSUE THREAD

**Issue by maojunhui666** [filebrowser/filebrowser#789]
**Description**
window xp下 从2.03升级到2.12无法运行了，老的版本又没有了下载

出现如下错误
C:\Documents and Settings\Administrator>C:\fb\filebrowser.exe
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Th
e specified procedure could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0x2043d9e0)
        /usr/local/go/src/syscall/dll_windows.go:311 +0x42
syscall.(*LazyProc).Addr(0x2043d9e0, 0x2114280)
        /usr/local/go/src/syscall/dll_windows.go:318 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x760, 0x9, 0x2046be84, 0x
8, 0x3, 0x2041a048)
        /usr/local/go/src/internal/syscall/windows/zsyscall_windows.go:353 +0x27

os.newFileStatFromGetFileInformationByHandle(0x204163c0, 0x15, 0x760, 0x0, 0x204
163c0, 0x15)
        /usr/local/go/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x20407088, 0x15, 0x0, 0x0, 0x20407088)
        /usr/local/go/src/os/stat_windows.go:55 +0x133
github.com/daaku/go%2ezipexe.OpenCloser(0x204163c0, 0x15, 0x204163c0, 0x15, 0x0,
 0x0, 0x0)
        /go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:26 +0x5e
github.com/GeertJohan/go%2erice.init.0()
        /go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/appended.go:41 +0x6f

**Comment by maojunhui666** [comment]
i have update my os to window7,it fixed the problem
