### ISSUE TITLE
Index out of range running locally on OSX

### ISSUE THREAD

**Issue by anxiousmodernman** [filebrowser/filebrowser#88]
I have a hugo site, generated with a fairly old hugo version. It's my personal blog, [public on GitHub](https://github.com/anxiousmodernman/coleman-dot-codes). I'd like to run a non-tls caddy locally for development, and watch my files with the hugo plugin to tweak the design, etc.

I keep different caddy builds in a folder called _caddies_. On both linux and osx builds I get an error on something like this command:

```
./caddies/osx/caddy -conf `pwd`/Caddyfile                                             [19:14:47]
Activating privacy features... done.
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x62d260, 0x420ff8100)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/hacdias/caddy-hugo.checkVersion(0x4211a8400, 0x13, 0x4211a8400)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/installer.go:95 +0x15b
github.com/hacdias/caddy-hugo.getPath(0x696ba0, 0x4211b20e0)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/installer.go:34 +0x6c4
github.com/hacdias/caddy-hugo.parse(0x4211d2240, 0x4211a4270, 0x6, 0x0, 0x4210d3738, 0x1003e)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/setup.go:144 +0x13a
github.com/hacdias/caddy-hugo.setup(0x4211d2240, 0x4, 0x6d3b47)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/setup.go:36 +0xb7
github.com/mholt/caddy.executeDirectives(0x4211b0680, 0x7fff5fbff3da, 0x52, 0xecc260, 0x26, 0x26, 0x4211a8280, 0x1, 0x1, 0x0, ...)
        /tmp/custombuild_2725_265827211/src/github.com/mholt/caddy/caddy.go:557 +0x597
github.com/mholt/caddy.startWithListenerFds(0xe79620, 0x4211aa440, 0x4211b0680, 0x0, 0x64, 0x0)
        /tmp/custombuild_2725_265827211/src/github.com/mholt/caddy/caddy.go:455 +0x39a
github.com/mholt/caddy.Start(0xe79620, 0x4211aa440, 0xe79620, 0x4211aa440, 0x0)
        /tmp/custombuild_2725_265827211/src/github.com/mholt/caddy/caddy.go:423 +0xff
github.com/mholt/caddy/caddy/caddymain.Run()
        /tmp/custombuild_2725_265827211/src/github.com/mholt/caddy/caddy/caddymain/run.go:105 +0x26b
main.main()
        /tmp/custombuild_2725_265827211/src/github.com/mholt/caddy/caddy/main.go:13 +0x1b
```

A panic in `setup(...)`. Interestingly, I do not see the file **installer.go** in this repo at all, but it appears in the stacktrace. My caddy build was generated from https://caddyserver.com/download today (Sat August 27, 2016) with filemanager, git, hugo, and prometheus plugins. 

Is there a typical cause for this error?

**Comment by hacdias** [comment]
Hey @anxiousmodernman! Sorry, I've fixed this bug some weeks ago, but the new version is not still available for download at caddyserver.com.

_Just pinging @mholt_

**Comment by anxiousmodernman** [comment]
I will try with a new build once the new code is on the build server. :)

**Comment by mholt** [comment]
Should be updated now.

**Comment by anxiousmodernman** [comment]
@mholt I just did a test from the build server, and it worked. Thank you! I myself opted to build from source last night, and that was simple enough. But I downloaded from the website and it worked.

**Comment by mikeifomin** [comment]
Hello I have the same crash but on Linux. 
I recently downloaded the binary form url
https://caddyserver.com/download/build?os=linux&arch=amd64&features=cors%2Cfilemanager%2Chugo

I run binary under docker.

```
goroutine 1 [running]:
panic(0x9c7d00, 0xc420010060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/hacdias/caddy-hugo.checkVersion(0xc42018ac20, 0x15, 0x11d6000)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/installer.go:95 +0x15b
github.com/hacdias/caddy-hugo.getPath(0xa285a0, 0xc4200f7dc0)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/installer.go:50 +0x67c
github.com/hacdias/caddy-hugo.parse(0xc420066360, 0xc4201464d0, 0xc, 0x0, 0xc420195728, 0x40efee)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/setup.go:144 +0x13a
github.com/hacdias/caddy-hugo.setup(0xc420066360, 0x4, 0xa60663)
        /home/caddy/go/src/github.com/hacdias/caddy-hugo/setup.go:36 +0xb7
github.com/mholt/caddy.executeDirectives(0xc4200f5860, 0x7ffd634bbf77, 0xe, 0x1223d80, 0x26, 0x26, 0xc4200ed780, 0x1, 0x1, 0x0, ...)
        /tmp/custombuild_8822_359321299/src/github.com/mholt/caddy/caddy.go:557 +0x597
github.com/mholt/caddy.startWithListenerFds(0x11d18e0, 0xc42003ad80, 0xc4200f5860, 0x0, 0x64, 0x0)
        /tmp/custombuild_8822_359321299/src/github.com/mholt/caddy/caddy.go:455 +0x39a
github.com/mholt/caddy.Start(0x11d18e0, 0xc42003ad80, 0x11d18e0, 0xc42003ad80, 0x0)
        /tmp/custombuild_8822_359321299/src/github.com/mholt/caddy/caddy.go:423 +0xff
github.com/mholt/caddy/caddy/caddymain.Run()
        /tmp/custombuild_8822_359321299/src/github.com/mholt/caddy/caddy/caddymain/run.go:104 +0x26b
main.main()
        /tmp/custombuild_8822_359321299/src/github.com/mholt/caddy/caddy/main.go:13 +0x1b
```

**Comment by anxiousmodernman** [comment]
@mikeifomin   How recently? It seems the build server was updated 10 minutes ago :)

**Comment by mholt** [comment]
@mikeifomin How recently? I updated it only about 12 minutes ago.

**Comment by mikeifomin** [comment]
Not so fast. about 1 hour ago! I'll try right now)

**Comment by mikeifomin** [comment]
Yes the crash is done. Now i have logs like this

```
It seems that you don't have 'hugo' on your PATH.
2016/08/29 16:41:06 It seems that you don't have 'hugo' on your PATH.
```

I think my case issue is solved

**Comment by mholt** [comment]
Cool. Yeah, the hugo plugin now requires installing the hugo binary yourself. (It's better this way.)

**Comment by hacdias** [comment]
Awesome :smile:

**Comment by mikeifomin** [comment]
@mholt sure.

P.S. big respect for such a fancy server like Caddy!
