### ISSUE TITLE
mipsle can not run,version 

### ISSUE THREAD

**Issue by carlsue** [filebrowser/filebrowser#949]
[root@MR:/root]#/usr/bin/filemanager  --port 80 --root /mnt/sda1
2019/12/26 01:52:51 No config file used
panic: could not locate box "../frontend/dist"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(...)
        /home/user/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/box.go:110
github.com/filebrowser/filebrowser/v2/http.getStaticHandlers(0x140acd0, 0x15fbcc0, 0x1420101, 0x600ac, 0x142ee40, 0x0)
        /home/user/buildroot-2019.11/output/host/temp/filebrowser/http/static.go:87 +0x2b0
github.com/filebrowser/filebrowser/v2/http.NewHandler(0x140acd0, 0x15fbcc0, 0x9f75e0, 0x16108b0, 0x15fbd40, 0x1622e00)
        /home/user/buildroot-2019.11/output/host/temp/filebrowser/http/http.go:20 +0x120
github.com/filebrowser/filebrowser/v2/cmd.glob..func12(0xeca0a0, 0x14c7a60, 0x0, 0x4, 0x0, 0x140acd0)
        /home/user/buildroot-2019.11/output/host/temp/filebrowser/cmd/root.go:133 +0x380
github.com/filebrowser/filebrowser/v2/cmd.python.func1(0xeca0a0, 0x14c7a60, 0x0, 0x4)
        /home/user/buildroot-2019.11/output/host/temp/filebrowser/cmd/utils.go:102 +0x218
github.com/spf13/cobra.(*Command).execute(0xeca0a0, 0x1422038, 0x4, 0x5, 0xeca0a0, 0x1422038)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x250
github.com/spf13/cobra.(*Command).ExecuteC(0xeca0a0, 0x151fc, 0x77955c, 0xed3eb0)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x290
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/filebrowser/filebrowser/v2/cmd.Execute()
        /home/user/buildroot-2019.11/output/host/temp/filebrowser/cmd/cmd.go:9 +0x44
main.main()
        /home/user/buildroot-2019.11/output/host/temp/filebrowser/main.go:11 +0x4c
[root@MR:/root]#filemanager version
File Browser v(untracked)/(unknown)

i git clone v2.0.16

**Comment by carlsue** [comment]
user@user-VirtualBox:/tmp/filebrowser/http$ rice embed-go
user@user-VirtualBox:/tmp/filebrowser/http$ GOOS=linux GOARCH=mipsle go build -v
github.com/filebrowser/filebrowser/v2/http
go build github.com/filebrowser/filebrowser/v2/http: /usr/lib/go-1.12/pkg/tool/linux_amd64/compile: signal: killed

**Comment by carlsue** [comment]
Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
main.go:6:2: cannot find package "github.com/filebrowser/filebrowser/v2/cmd" in any of:
	/usr/lib/go-1.10/src/github.com/filebrowser/filebrowser/v2/cmd (from $GOROOT)
	/home/admini/go/src/github.com/filebrowser/filebrowser/v2/cmd (from $GOPATH)

**Comment by carlsue** [comment]
here you are,version v2.11.0
[filebrowser.zip](https://github.com/filebrowser/filebrowser/files/5972822/filebrowser.zip)
